### PR TITLE
Use grid framework for extensions

### PR DESCRIPTION
**Pull request by unnonouno**
I used grid framework for responsible design. I also adjusted padding and margin.
This pr includes #45 

image
image

### CODE REVIEW

**Comment by niboshi** [comment]
As in the second screenshot, the boxes will be stretched if the screen is not wide enough.
I think it's not great because there's a large area of blank spaces.

**Comment by unnonouno** [comment]
This is for mobile phones. In small devices, I think it is better to use single column.

**Comment by niboshi** [comment]
As you say, it looks better in mobile phones. But in desktop with smaller width (as in the second screenshot), it doesn't look good. Can you fix?

**Comment by niboshi** [comment]
Or maybe we can fix it after merge?

**Comment by unnonouno** [comment]
How about this?
image

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
